source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem 'bulma-rails', '~> 0.9.2'
gem "rails", "~> 7.0.1"
gem "sprockets-rails"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem 'devise', github: 'heartcombo/devise', branch: 'main'
gem 'image_processing', '~> 1.12', '>= 1.12.1'
gem "aws-sdk-s3", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
  gem 'guard', '~> 2.18'
  gem 'guard-livereload', '~> 2.5', require: false
  gem "better_errors"
  gem "binding_of_caller"
  gem "sqlite3", "~> 1.4"
end

group :production do
  gem 'pg', '~> 1.3'
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
